argo-cd:
  ## ArgoCD configuration
  ## Ref: https://github.com/argoproj/argo-cd
  ##
  ## Server
  server:
    ## ArgoCD config
    ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    clusterAdminAccess:
      enabled: false
    configEnabled: true
    config:
      repositories: |
        - name: argo-helm
          type: helm
          url: https://argoproj.github.io/argo-helm
      accounts.image-updater: apiKey
    rbacConfig:
      policy.csv: |
        p, role:image-updater, applications, get, */*, allow
        p, role:image-updater, applications, update, */*, allow
        g, image-updater, role:image-updater
    extraArgs:
    - --insecure
  controller:
    clusterAdminAccess:
      enabled: false