apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: {{ .Release.Namespace }}
spec:
  project: argocd
  source:
        directory:
          recurse: true
        path: argocd-apps
        repoURL: https://github.com/0m1xa/argocd-client1.git
        targetRevision: HEAD
  destination:
        namespace: {{ .Release.Namespace }}
        server: https://kubernetes.default.svc
  syncPolicy:
        automated:
          prune: true
          selfHeal: true
