apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller-ro
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
  - get
  - watch
- nonResourceURLs:
  - '*'
  verbs:
  - list
  - get
  - watch