{{- if not (index .Values "argo-cd" "controller" "clusterAdminAccess" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-ro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-ro
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: {{ .Release.Namespace }}
{{- end }}