{{- if not (index .Values "argo-cd" "controller" "clusterAdminAccess" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
{{- end }}